Configs:
  Segmentation: False
  Quantification: True
  Gap Analysis: True

Segmentation:
  Number of Labels: 48
  Max Iterations: 30
  Normalized Hue Value: 1.0
  Color Threshold: 0.2
  Min Size: 64
  Max Size: 2048

Detection:
  Dark Line: False
  Min Line Width: 1
  Max Line Width: 5
  Low Contrast: 50
  High Contrast: 100
  Extend Line: False
  Correct Position: False
  Minimum Branch Length: 5
  Maximum Branch Length: 0

Quantification:
  Maximum Display HDM: 230
  Contrast Enhancement: 0.1
  Minimum Branch Length: 5
  Minimum Skeleton Size: 10
  Minimum Hole Area: 8 
  Minimum Curvature Window: 10
  Maximum Curvature Window: 30
  Curvature Window Step: 10

Gap Analysis:
  Minimum Gap Diameter: 10